### PR TITLE
Feature/token-sale-box mobile view with multi language support implemented

### PR DESCRIPTION
**Pull request by SeunghunSunmoonLee**
ciaran is looking at mobile view design for token sale box. 

Mobile view should look the same as desktop design? It can't be the same since the coin image height to container height will be much smaller than before. Another challenge is font size should be reduced significantly to fit into 65% of the container with

### CODE REVIEW

**Comment by chutium** [comment]
Thanks, let's wait until the mobile view fixed, because this box located at the very top of the page, we'd better make sure that everything looks fine here.

**Comment by geastwood** [comment]
Hi Lee, Would you setup your editor to understand the js and css linting rules. If it correctly setup it should give you warnings. You can also run `yarn run lint:js` and `yarn run lint:css` to see all the warnings. Plus setting up *prettier* could really save a lot of effort discussing about styles.

**Comment by chutium** [comment]
@geastwood so your opinion is approved or not? I agree that linting rules should be applied, the code indentation is not that well here.

**Comment by geastwood** [comment]
It's already approved.

**Comment by chutium** [comment]
@geastwood I saw it... therefore I'm asking... so you mean the problem with verticalAlign, ares-coin and linting rules do not need to be fixed?

**Pull request merged**
